"""initial_normalized_schema

Revision ID: 1750d0754386
Revises:
Create Date: 2026-07-26 18:12:44.069447

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1750d0754386'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_basis_id', sa.String(length=3), nullable=False),
    sa.Column('delivery_basis_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_bases_delivery_basis_id'), 'delivery_bases', ['delivery_basis_id'], unique=True)
    op.create_table('delivery_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_type_id', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_types_delivery_type_id'), 'delivery_types', ['delivery_type_id'], unique=True)
    op.create_table('oil_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_product_id', sa.String(length=20), nullable=False),
    sa.Column('exchange_product_name', sa.String(length=255), nullable=True),
    sa.Column('oil_id', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oil_products_exchange_product_id'), 'oil_products', ['exchange_product_id'], unique=True)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('delivery_basis_id', sa.Integer(), nullable=True),
    sa.Column('delivery_type_id', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['delivery_basis_id'], ['delivery_bases.id'], ),
    sa.ForeignKeyConstraint(['delivery_type_id'], ['delivery_types.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['oil_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'delivery_basis_id', 'delivery_type_id', 'date', name='uix_trade_unique')
    )
    op.create_index(op.f('ix_trades_date'), 'trades', ['date'], unique=False)
    op.create_index(op.f('ix_trades_delivery_basis_id'), 'trades', ['delivery_basis_id'], unique=False)
    op.create_index(op.f('ix_trades_delivery_type_id'), 'trades', ['delivery_type_id'], unique=False)
    op.create_index(op.f('ix_trades_product_id'), 'trades', ['product_id'], unique=False)
    op.create_index(op.f('ix_trades_url'), 'trades', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_url'), table_name='trades')
    op.drop_index(op.f('ix_trades_product_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_delivery_type_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_delivery_basis_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_date'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_oil_products_exchange_product_id'), table_name='oil_products')
    op.drop_table('oil_products')
    op.drop_index(op.f('ix_delivery_types_delivery_type_id'), table_name='delivery_types')
    op.drop_table('delivery_types')
    op.drop_index(op.f('ix_delivery_bases_delivery_basis_id'), table_name='delivery_bases')
    op.drop_table('delivery_bases')
    # ### end Alembic commands ###
