"""add_unique_date_remove_unique_url

Revision ID: 40fd6ef97e41
Revises: 429b9702bfa4
Create Date: 2026-07-23 16:20:48.017664

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '40fd6ef97e41'
down_revision: str | Sequence[str] | None = '429b9702bfa4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_results_url'), 'results', type_='unique')
    op.drop_index(op.f('ix_results_date'), table_name='results')
    op.create_index(op.f('ix_results_date'), 'results', ['date'], unique=True)
    op.drop_index(op.f('ix_results_url'), table_name='results')
    op.create_index(op.f('ix_results_url'), 'results', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_url'), table_name='results')
    op.create_index(op.f('ix_results_url'), 'results', ['url'], unique=True)
    op.drop_index(op.f('ix_results_date'), table_name='results')
    op.create_index(op.f('ix_results_date'), 'results', ['date'], unique=False)
    op.create_unique_constraint(op.f('uq_results_url'), 'results', ['url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
