"""init tables

Revision ID: c4787baeab1f
Revises: 
Create Date: 2026-08-04 11:30:49.815907

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c4787baeab1f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_bases',
    sa.Column('delivery_basis_id', sa.String(length=3), nullable=False),
    sa.Column('delivery_basis_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('delivery_basis_id')
    )
    op.create_table('delivery_types',
    sa.Column('delivery_type_id', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('delivery_type_id')
    )
    op.create_table('exchanges',
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('exchange_id')
    )
    op.create_index(op.f('ix_exchanges_name'), 'exchanges', ['name'], unique=True)
    op.create_table('oil_products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('exchange_product_id', sa.String(length=20), nullable=False),
    sa.Column('exchange_product_name', sa.String(length=255), nullable=True),
    sa.Column('oil_id', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.exchange_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('exchange_id', 'exchange_product_id', name='uix_oil_product_exchange')
    )
    op.create_index(op.f('ix_oil_products_exchange_id'), 'oil_products', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_oil_products_exchange_product_id'), 'oil_products', ['exchange_product_id'], unique=False)
    op.create_table('trades',
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('exchange_trade_id', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('delivery_basis_id', sa.String(length=3), nullable=True),
    sa.Column('delivery_type_id', sa.String(length=1), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['delivery_basis_id'], ['delivery_bases.delivery_basis_id'], ),
    sa.ForeignKeyConstraint(['delivery_type_id'], ['delivery_types.delivery_type_id'], ),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.exchange_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['oil_products.product_id'], ),
    sa.PrimaryKeyConstraint('trade_id'),
    sa.UniqueConstraint('exchange_id', 'exchange_trade_id', name='uix_exchange_trade')
    )
    op.create_index(op.f('ix_trades_date'), 'trades', ['date'], unique=False)
    op.create_index(op.f('ix_trades_delivery_basis_id'), 'trades', ['delivery_basis_id'], unique=False)
    op.create_index(op.f('ix_trades_delivery_type_id'), 'trades', ['delivery_type_id'], unique=False)
    op.create_index(op.f('ix_trades_exchange_id'), 'trades', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_trades_product_id'), 'trades', ['product_id'], unique=False)
    op.create_index(op.f('ix_trades_url'), 'trades', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_url'), table_name='trades')
    op.drop_index(op.f('ix_trades_product_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_exchange_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_delivery_type_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_delivery_basis_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_date'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_oil_products_exchange_product_id'), table_name='oil_products')
    op.drop_index(op.f('ix_oil_products_exchange_id'), table_name='oil_products')
    op.drop_table('oil_products')
    op.drop_index(op.f('ix_exchanges_name'), table_name='exchanges')
    op.drop_table('exchanges')
    op.drop_table('delivery_types')
    op.drop_table('delivery_bases')
    # ### end Alembic commands ###
